# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\"$\n\tgm_signup\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0b\n\x03PSW\x18\x02 \x01(\t\"%\n\tgm_friend\x12\x0b\n\x03SID\x18\x01 \x01(\t\x12\x0b\n\x03\x44ID\x18\x02 \x01(\t\"]\n\x0fGeneralMessages\x12\n\n\x02RC\x18\x01 \x01(\t\x12\n\n\x02SC\x18\x02 \x01(\t\x12\n\n\x02\x44T\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x41TA\x18\x04 \x01(\t\x12\x0b\n\x03SIP\x18\x05 \x01(\t\x12\x0b\n\x03\x44IP\x18\x06 \x01(\t\"3\n\x08\x43lientAS\x12\x0b\n\x03IDc\x18\x01 \x01(\t\x12\r\n\x05IDtgs\x18\x02 \x01(\t\x12\x0b\n\x03TS1\x18\x03 \x01(\t\"[\n\x08\x41SClient\x12\r\n\x05Kctgs\x18\x01 \x01(\t\x12\r\n\x05IDtgs\x18\x02 \x01(\t\x12\x0b\n\x03TS2\x18\x03 \x01(\t\x12\x11\n\tLifetime2\x18\x04 \x01(\t\x12\x11\n\tTickettgs\x18\x05 \x01(\t\"c\n\tTickettgs\x12\r\n\x05Kctgs\x18\x01 \x01(\t\x12\x0b\n\x03IDc\x18\x02 \x01(\t\x12\x0b\n\x03\x41\x44\x63\x18\x03 \x01(\t\x12\r\n\x05IDtgs\x18\x04 \x01(\t\x12\x0b\n\x03TS2\x18\x05 \x01(\t\x12\x11\n\tLifetime2\x18\x06 \x01(\t\"C\n\tClientTGS\x12\x0b\n\x03IDv\x18\x01 \x01(\t\x12\x11\n\tTickettgs\x18\x02 \x01(\t\x12\x16\n\x0e\x41uthenticatorC\x18\x03 \x01(\t\"C\n\tTGSClient\x12\x0b\n\x03Kcv\x18\x01 \x01(\t\x12\x0b\n\x03IDv\x18\x02 \x01(\t\x12\x0b\n\x03TS4\x18\x03 \x01(\t\x12\x0f\n\x07Ticketv\x18\x04 \x01(\t\"8\n\x0f\x41uthenticatorC3\x12\x0b\n\x03IDc\x18\x01 \x01(\t\x12\x0b\n\x03\x41\x44\x63\x18\x02 \x01(\t\x12\x0b\n\x03TS3\x18\x03 \x01(\t\"]\n\x07Ticketv\x12\x0b\n\x03Kcv\x18\x01 \x01(\t\x12\x0b\n\x03IDc\x18\x02 \x01(\t\x12\x0b\n\x03\x41\x44\x63\x18\x03 \x01(\t\x12\x0b\n\x03IDv\x18\x04 \x01(\t\x12\x0b\n\x03TS4\x18\x05 \x01(\t\x12\x11\n\tLifetime4\x18\x06 \x01(\t\"2\n\x07\x43lientV\x12\x0f\n\x07Ticketv\x18\x01 \x01(\t\x12\x16\n\x0e\x41uthenticatorC\x18\x02 \x01(\t\"8\n\x0f\x41uthenticatorC5\x12\x0b\n\x03IDc\x18\x01 \x01(\t\x12\x0b\n\x03\x41\x44\x63\x18\x02 \x01(\t\x12\x0b\n\x03TS5\x18\x03 \x01(\t\"\x16\n\x07VClient\x12\x0b\n\x03TS5\x18\x01 \x01(\tb\x06proto3')
)




_GM_SIGNUP = _descriptor.Descriptor(
  name='gm_signup',
  full_name='gm_signup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='gm_signup.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PSW', full_name='gm_signup.PSW', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=53,
)


_GM_FRIEND = _descriptor.Descriptor(
  name='gm_friend',
  full_name='gm_friend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SID', full_name='gm_friend.SID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DID', full_name='gm_friend.DID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=92,
)


_GENERALMESSAGES = _descriptor.Descriptor(
  name='GeneralMessages',
  full_name='GeneralMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RC', full_name='GeneralMessages.RC', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SC', full_name='GeneralMessages.SC', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DT', full_name='GeneralMessages.DT', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DATA', full_name='GeneralMessages.DATA', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SIP', full_name='GeneralMessages.SIP', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DIP', full_name='GeneralMessages.DIP', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=187,
)


_CLIENTAS = _descriptor.Descriptor(
  name='ClientAS',
  full_name='ClientAS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IDc', full_name='ClientAS.IDc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IDtgs', full_name='ClientAS.IDtgs', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TS1', full_name='ClientAS.TS1', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=240,
)


_ASCLIENT = _descriptor.Descriptor(
  name='ASClient',
  full_name='ASClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Kctgs', full_name='ASClient.Kctgs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IDtgs', full_name='ASClient.IDtgs', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TS2', full_name='ASClient.TS2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Lifetime2', full_name='ASClient.Lifetime2', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Tickettgs', full_name='ASClient.Tickettgs', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=333,
)


_TICKETTGS = _descriptor.Descriptor(
  name='Tickettgs',
  full_name='Tickettgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Kctgs', full_name='Tickettgs.Kctgs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IDc', full_name='Tickettgs.IDc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ADc', full_name='Tickettgs.ADc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IDtgs', full_name='Tickettgs.IDtgs', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TS2', full_name='Tickettgs.TS2', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Lifetime2', full_name='Tickettgs.Lifetime2', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=434,
)


_CLIENTTGS = _descriptor.Descriptor(
  name='ClientTGS',
  full_name='ClientTGS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IDv', full_name='ClientTGS.IDv', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Tickettgs', full_name='ClientTGS.Tickettgs', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AuthenticatorC', full_name='ClientTGS.AuthenticatorC', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=503,
)


_TGSCLIENT = _descriptor.Descriptor(
  name='TGSClient',
  full_name='TGSClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Kcv', full_name='TGSClient.Kcv', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IDv', full_name='TGSClient.IDv', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TS4', full_name='TGSClient.TS4', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Ticketv', full_name='TGSClient.Ticketv', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=572,
)


_AUTHENTICATORC3 = _descriptor.Descriptor(
  name='AuthenticatorC3',
  full_name='AuthenticatorC3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IDc', full_name='AuthenticatorC3.IDc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ADc', full_name='AuthenticatorC3.ADc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TS3', full_name='AuthenticatorC3.TS3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=630,
)


_TICKETV = _descriptor.Descriptor(
  name='Ticketv',
  full_name='Ticketv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Kcv', full_name='Ticketv.Kcv', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IDc', full_name='Ticketv.IDc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ADc', full_name='Ticketv.ADc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IDv', full_name='Ticketv.IDv', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TS4', full_name='Ticketv.TS4', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Lifetime4', full_name='Ticketv.Lifetime4', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=632,
  serialized_end=725,
)


_CLIENTV = _descriptor.Descriptor(
  name='ClientV',
  full_name='ClientV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Ticketv', full_name='ClientV.Ticketv', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AuthenticatorC', full_name='ClientV.AuthenticatorC', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=727,
  serialized_end=777,
)


_AUTHENTICATORC5 = _descriptor.Descriptor(
  name='AuthenticatorC5',
  full_name='AuthenticatorC5',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IDc', full_name='AuthenticatorC5.IDc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ADc', full_name='AuthenticatorC5.ADc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TS5', full_name='AuthenticatorC5.TS5', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=779,
  serialized_end=835,
)


_VCLIENT = _descriptor.Descriptor(
  name='VClient',
  full_name='VClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TS5', full_name='VClient.TS5', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=837,
  serialized_end=859,
)

DESCRIPTOR.message_types_by_name['gm_signup'] = _GM_SIGNUP
DESCRIPTOR.message_types_by_name['gm_friend'] = _GM_FRIEND
DESCRIPTOR.message_types_by_name['GeneralMessages'] = _GENERALMESSAGES
DESCRIPTOR.message_types_by_name['ClientAS'] = _CLIENTAS
DESCRIPTOR.message_types_by_name['ASClient'] = _ASCLIENT
DESCRIPTOR.message_types_by_name['Tickettgs'] = _TICKETTGS
DESCRIPTOR.message_types_by_name['ClientTGS'] = _CLIENTTGS
DESCRIPTOR.message_types_by_name['TGSClient'] = _TGSCLIENT
DESCRIPTOR.message_types_by_name['AuthenticatorC3'] = _AUTHENTICATORC3
DESCRIPTOR.message_types_by_name['Ticketv'] = _TICKETV
DESCRIPTOR.message_types_by_name['ClientV'] = _CLIENTV
DESCRIPTOR.message_types_by_name['AuthenticatorC5'] = _AUTHENTICATORC5
DESCRIPTOR.message_types_by_name['VClient'] = _VCLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

gm_signup = _reflection.GeneratedProtocolMessageType('gm_signup', (_message.Message,), dict(
  DESCRIPTOR = _GM_SIGNUP,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:gm_signup)
  ))
_sym_db.RegisterMessage(gm_signup)

gm_friend = _reflection.GeneratedProtocolMessageType('gm_friend', (_message.Message,), dict(
  DESCRIPTOR = _GM_FRIEND,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:gm_friend)
  ))
_sym_db.RegisterMessage(gm_friend)

GeneralMessages = _reflection.GeneratedProtocolMessageType('GeneralMessages', (_message.Message,), dict(
  DESCRIPTOR = _GENERALMESSAGES,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:GeneralMessages)
  ))
_sym_db.RegisterMessage(GeneralMessages)

ClientAS = _reflection.GeneratedProtocolMessageType('ClientAS', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTAS,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ClientAS)
  ))
_sym_db.RegisterMessage(ClientAS)

ASClient = _reflection.GeneratedProtocolMessageType('ASClient', (_message.Message,), dict(
  DESCRIPTOR = _ASCLIENT,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ASClient)
  ))
_sym_db.RegisterMessage(ASClient)

Tickettgs = _reflection.GeneratedProtocolMessageType('Tickettgs', (_message.Message,), dict(
  DESCRIPTOR = _TICKETTGS,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Tickettgs)
  ))
_sym_db.RegisterMessage(Tickettgs)

ClientTGS = _reflection.GeneratedProtocolMessageType('ClientTGS', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTGS,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ClientTGS)
  ))
_sym_db.RegisterMessage(ClientTGS)

TGSClient = _reflection.GeneratedProtocolMessageType('TGSClient', (_message.Message,), dict(
  DESCRIPTOR = _TGSCLIENT,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:TGSClient)
  ))
_sym_db.RegisterMessage(TGSClient)

AuthenticatorC3 = _reflection.GeneratedProtocolMessageType('AuthenticatorC3', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATORC3,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:AuthenticatorC3)
  ))
_sym_db.RegisterMessage(AuthenticatorC3)

Ticketv = _reflection.GeneratedProtocolMessageType('Ticketv', (_message.Message,), dict(
  DESCRIPTOR = _TICKETV,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Ticketv)
  ))
_sym_db.RegisterMessage(Ticketv)

ClientV = _reflection.GeneratedProtocolMessageType('ClientV', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTV,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ClientV)
  ))
_sym_db.RegisterMessage(ClientV)

AuthenticatorC5 = _reflection.GeneratedProtocolMessageType('AuthenticatorC5', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATORC5,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:AuthenticatorC5)
  ))
_sym_db.RegisterMessage(AuthenticatorC5)

VClient = _reflection.GeneratedProtocolMessageType('VClient', (_message.Message,), dict(
  DESCRIPTOR = _VCLIENT,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:VClient)
  ))
_sym_db.RegisterMessage(VClient)


# @@protoc_insertion_point(module_scope)
