# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_redis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server_redis.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12server_redis.proto\"\"\n\x07User_AI\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0b\n\x03PSW\x18\x02 \x01(\t\"@\n\x0bUser_online\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0b\n\x03STD\x18\x02 \x01(\t\x12\n\n\x02IP\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\tb\x06proto3')
)




_USER_AI = _descriptor.Descriptor(
  name='User_AI',
  full_name='User_AI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='User_AI.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PSW', full_name='User_AI.PSW', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=56,
)


_USER_ONLINE = _descriptor.Descriptor(
  name='User_online',
  full_name='User_online',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='User_online.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='STD', full_name='User_online.STD', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IP', full_name='User_online.IP', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='User_online.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['User_AI'] = _USER_AI
DESCRIPTOR.message_types_by_name['User_online'] = _USER_ONLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User_AI = _reflection.GeneratedProtocolMessageType('User_AI', (_message.Message,), dict(
  DESCRIPTOR = _USER_AI,
  __module__ = 'server_redis_pb2'
  # @@protoc_insertion_point(class_scope:User_AI)
  ))
_sym_db.RegisterMessage(User_AI)

User_online = _reflection.GeneratedProtocolMessageType('User_online', (_message.Message,), dict(
  DESCRIPTOR = _USER_ONLINE,
  __module__ = 'server_redis_pb2'
  # @@protoc_insertion_point(class_scope:User_online)
  ))
_sym_db.RegisterMessage(User_online)


# @@protoc_insertion_point(module_scope)
